### ISSUE TITLE
Warning with blocking call to load default certs occurring

### ISSUE THREAD

**Issue by rsocko** [jordanruthe/homeassistant-phyn#35]
Noticed the following warning getting logged for the Phyn integration. I haven't (yet) had a chance to try to dig in and debug what's occurring. 

Running latest 2024.10.0 release.

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 10:55:36 PM (1 occurrences)
Last logged: 10:55:36 PM

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f543b4550>,) inside the event loop by custom integration 'phyn' at custom_components/phyn/__init__.py, line 64: await client.mqtt.connect() (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/jordanruthe/homeassistant-phyn/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/phyn/__init__.py", line 64, in async_setup_entry await client.mqtt.connect()

**Comment by ptr727** [comment]
Reasonably easy fox for this, e.g. here is a similar fix from the same type of report, just do what the error says.
https://github.com/loopj/home-assistant-vantage/commit/14eaae27f4e146860e5d7a0797e4fb4e65b1783b
https://github.com/loopj/aiovantage/pull/142/files
